from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from analyze_sanskrit_token_splits import path_record, span_candidates, top_split_paths
from indic_transliteration import sanscript
from indicnlp.normalize.indic_normalize import IndicNormalizerFactory

from build_sanskrit_token_graph import load_lexicon


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Probe unmatched OCR Sanskrit tokens with normalization, transliteration, sandhi analysis, and morphological tagging."
    )
    parser.add_argument(
        "unmatched_json",
        nargs="?",
        default="phase2_input/page_002_token_graph_akshara/unmatched_tokens.json",
        help="Path to the unmatched token JSON generated by the token graph pipeline",
    )
    parser.add_argument(
        "--output-dir",
        default="phase2_input/page_002_parser_probe",
        help="Directory where parser probe outputs will be written",
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=20,
        help="Maximum unmatched tokens to probe, in input order",
    )
    parser.add_argument(
        "--timeout-seconds",
        type=int,
        default=20,
        help="Timeout per parser subprocess call",
    )
    parser.add_argument(
        "--lexicon",
        default="resources/modern_sanskrit_seed_lexicon.tsv",
        help="Lexicon TSV used for fuzzy split fallback candidates.",
    )
    parser.add_argument(
        "--max-dp-candidates",
        type=int,
        default=5,
        help="Maximum dynamic-programming split candidates stored per token.",
    )
    return parser.parse_args()


def load_unmatched_tokens(path: Path) -> list[dict[str, object]]:
    if not path.is_file():
        raise FileNotFoundError(f"Unmatched token file not found: {path}")

    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("Unmatched token file must contain a JSON list.")
    return data


def normalized_token(token: str, normalizer) -> str:
    return normalizer.normalize(token).strip()


def transliteration_views(token: str) -> dict[str, str]:
    return {
        "devanagari": token,
        "slp1": sanscript.transliterate(token, sanscript.DEVANAGARI, sanscript.SLP1),
        "iast": sanscript.transliterate(token, sanscript.DEVANAGARI, sanscript.IAST),
    }


def run_parser_command(command: str, token: str, timeout_seconds: int) -> dict[str, object]:
    completed = subprocess.run(
        ["sanskrit_parser", command, token],
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
        check=False,
    )
    return {
        "command": command,
        "returncode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def has_substantive_analysis(command: str, result: dict[str, object]) -> bool:
    combined = "\n".join([str(result.get("stdout", "")), str(result.get("stderr", ""))])
    if command == "sandhi":
        return "Split:" in combined and "No Splits Found" not in combined
    if command == "tags":
        return "(" in combined and "Morphological tags:" in combined
    return False


def dp_split_candidates(normalized: str, lexicon, max_candidates: int) -> list[dict[str, object]]:
    if not normalized:
        return []
    candidates_by_start = span_candidates(normalized, lexicon, score_threshold=0.72)
    paths = top_split_paths(
        normalized,
        candidates_by_start,
        top_k=max(1, max_candidates),
        skip_penalty=0.55,
        split_penalty=0.08,
    )
    return [path_record(path) for path in paths]


def probe_token(token_record: dict[str, object], normalizer, timeout_seconds: int, lexicon, max_dp_candidates: int) -> dict[str, object]:
    surface = str(token_record.get("token", "")).strip()
    normalized = normalized_token(surface, normalizer)

    return {
        "token": surface,
        "count": int(token_record.get("count", 0)),
        "chunk_indices": token_record.get("chunk_indices", []),
        "line_indices": token_record.get("line_indices", []),
        "normalized": normalized,
        "transliterations": transliteration_views(normalized or surface),
        "sandhi": run_parser_command("sandhi", normalized or surface, timeout_seconds=timeout_seconds),
        "tags": run_parser_command("tags", normalized or surface, timeout_seconds=timeout_seconds),
        "dp_candidates": dp_split_candidates(normalized, lexicon, max_candidates=max_dp_candidates),
    }


def summary_lines(probes: list[dict[str, object]]) -> list[str]:
    lines = ["# Unmatched Token Parser Probe", ""]
    for probe in probes:
        lines.append(f"## {probe['token']}")
        lines.append("")
        lines.append(f"Normalized: {probe['normalized']}")
        lines.append(f"SLP1: {probe['transliterations']['slp1']}")
        lines.append(f"IAST: {probe['transliterations']['iast']}")
        lines.append(f"Count: {probe['count']}")
        lines.append(f"Chunks: {probe['chunk_indices']}")
        lines.append(f"Lines: {probe['line_indices']}")
        lines.append("")
        lines.append("### Sandhi")
        lines.append("")
        sandhi_stdout = str(probe["sandhi"]["stdout"]).strip() or "<no output>"
        lines.append(sandhi_stdout)
        lines.append("")
        lines.append("### Tags")
        lines.append("")
        tags_stdout = str(probe["tags"]["stdout"]).strip() or "<no output>"
        lines.append(tags_stdout)
        lines.append("")
        if probe.get("dp_candidates"):
            lines.append("### DP Split Candidates")
            lines.append("")
            for candidate in probe["dp_candidates"]:
                lines.append(
                    f"- {candidate['split']} | score={candidate['score']} | skipped={candidate['skipped_chars']} | meaning={candidate['interpretation'] or '<none>'}"
                )
            lines.append("")
    return lines


def write_outputs(output_dir: Path, input_path: Path, probes: list[dict[str, object]]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    summary = {
        "source_unmatched": str(input_path),
        "token_probe_count": len(probes),
        "sandhi_hits": sum(1 for probe in probes if has_substantive_analysis("sandhi", probe["sandhi"])),
        "tag_hits": sum(1 for probe in probes if has_substantive_analysis("tags", probe["tags"])),
        "dp_hits": sum(1 for probe in probes if probe.get("dp_candidates")),
    }

    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    (output_dir / "probe_results.json").write_text(json.dumps(probes, indent=2, ensure_ascii=False), encoding="utf-8")
    (output_dir / "probe_report.md").write_text("\n".join(summary_lines(probes)), encoding="utf-8")


def main() -> int:
    args = parse_args()
    input_path = Path(args.unmatched_json)
    output_dir = Path(args.output_dir)

    try:
        unmatched = load_unmatched_tokens(input_path)
        lexicon = load_lexicon(Path(args.lexicon))
    except (FileNotFoundError, ValueError) as exc:
        print(exc)
        return 1

    normalizer = IndicNormalizerFactory().get_normalizer("sa")
    selected = unmatched[: max(0, args.max_tokens)]
    probes = [
        probe_token(
            token_record,
            normalizer,
            timeout_seconds=args.timeout_seconds,
            lexicon=lexicon,
            max_dp_candidates=args.max_dp_candidates,
        )
        for token_record in selected
    ]

    write_outputs(output_dir, input_path, probes)
    print(f"Probed {len(probes)} unmatched token(s) in {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())